ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER JORGEI IDENTIFIED BY 0000
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 100M ON SYSTEM;

CREATE ROLE PERMI;

GRANT CREATE SESSION, CREATE TABLE,CREATE VIEW, CREATE
PROCEDURE, UPDATE ANY TABLE TO PERMI;
GRANT PERMI TO JORGEI;
GRANT UPDATE ON FRUTAS TO PERMI;

CREATE TABLE FRUTAS(
    ID NUMERIC,
    FRUTA VARCHAR2(20)
);

INSERT INTO FRUTAS VALUES(1, 'UVAS');
INSERT INTO FRUTAS VALUES(1, 'MANZANAS');
INSERT INTO FRUTAS VALUES(1, 'PERAS');
INSERT INTO FRUTAS VALUES(4, 'GUAYABAS');
SELECT * FROM FRUTAS;

CREATE USER HIJO IDENTIFIED BY 0000;
GRANT PERMI TO HIJO;

SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'PERMI';

REVOKE UPDATE ON frutas FROM permi;

REVOKE all ON frutas FROM permi;

GRANT SELECT ON FRUTAS to hijo;
GRANT INSERT ON FRUTAS TO HIJO;
GRANT INSERT ON FRUTAS TO PERMI,JORGEI;
GRANT UPDATE ON FRUTAS TO PERMI,JORGEI;

SELECT * FROM JORGEI.FRUTAS;

INSERT INTO JORGEI.frutas VALUES(4, 'BANANOS');
UPDATE JORGEI.frutas SET FRUTA ='MANGOS' WHERE
FRUTA='BANANOS';

create SYNONYM comestibles for jorgei.frutas;
INSERT INTO comestibles VALUES(6, 'MELON');

SELECT * FROM comestibles;

---

GRANT CONNECT, RESOURCE TO JORGEI;
CREATE VIEW vista_frutas AS
SELECT FRUTA
FROM FRUTAS;

GRANT SELECT ON vista_frutas TO JORGEI;

--JORGEI
--HIJO
CREATE USER UNO IDENTIFIED BY 0000;
CREATE USER DOS IDENTIFIED BY 0000;

GRANT CREATE SESSION, CREATE TABLE,CREATE VIEW, CREATE
PROCEDURE, UPDATE ANY TABLE TO UNO,DOS;
