alter session set "_ORACLE_SCRIPT"=TRUE;

--CREAR USUARIO
CREATE USER SuperRaton IDENTIFIED BY 0000 DEFAULT TABLESPACE SYSTEM TEMPORARY TABLESPACE TEMP QUOTA 10M ON SYSTEM;

--Dar Permisos a usuario
GRANT CREATE SESSION TO SuperRaton;
GRANT CREATE ANY TABLE TO SuperRaton;
GRANT CREATE ROLE TO SuperRaton;
GRANT CREATE USER TO SuperRaton;
GRANT CREATE VIEW TO SuperRaton;
GRANT CREATE ANY INDEX TO SuperRaton;
GRANT CREATE TRIGGER TO SuperRaton;
GRANT CREATE PROCEDURE TO SuperRaton;
GRANT CREATE SEQUENCE TO SuperRaton;

