SELECT * FROM CATEGORIAS;

SELECT * FROM CATEGORIAS WHERE NOMBRECAT = 'CARNICOS';

SELECT * FROM ORDENES WHERE DESCUENTO >= 8;

SELECT * FROM ORDENES WHERE DESCUENTO >= 8 AND EMPLEADOID >= 3;

Select PRODUCTOID, COUNT(PRODUCTOID) From PRODUCTOS GROUP BY PRODUCTOID;

select descripcion, categoriaid, existencia From productos order by categoriaid;

select descripcion, categoriaid, existencia From productos order by categoriaid desc, descripcion desc;

select CLIENTEID, COUNT(CLIENTEID) "NUMERO ORDENES" from ordenes GROUP BY CLIENTEID;

SELECT COUNT(PROVEEDORID) FROM PRODUCTOS GROUP BY categoriaid;

Select count(proveedorid) From productos Group by categoriaid Having (count(proveedorid)>3);

SELECT P.DESCRIPCION, P.PRECIOUNIT, P.EXISTENCIA, C.NOMBRECAT FROM PRODUCTOS P JOIN CATEGORIAS C ON P.CATEGORIAID = C.CATEGORIAID ORDER BY P.EXISTENCIA ASC;

SELECT E.NOMBRE, E.APELLIDO, O.CLIENTEID FROM EMPLEADOS E JOIN ORDENES O ON E.EMPLEADOID = O.EMPLEADOID; 


